<a href="https://colab.research.google.com/github/Chrahuldeveloper/Appyfounders/blob/main/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [ ]:
import kagglehub

path = kagglehub.dataset_download("nehalbirla/vehicle-dataset-from-cardekho")

os.listdir(path)

Using Colab cache for faster access to the 'vehicle-dataset-from-cardekho' dataset.

['car data.csv',
 'car details v4.csv',
 'CAR DETAILS FROM CAR DEKHO.csv',
 'Car details v3.csv']

In [ ]:
df = pd.read_csv(path + "/car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [ ]:
df = df.drop(["Car_Name", "Seller_Type", "Owner","Fuel_Type"], axis=1)
df["Transmission"] = df["Transmission"].map({"Manual": 1, "Automatic": 0})

df

     Year  Selling_Price  Present_Price  Kms_Driven  Transmission
0    2014           3.35           5.59       27000             1
1    2013           4.75           9.54       43000             1
2    2017           7.25           9.85        6900             1
3    2011           2.85           4.15        5200             1
4    2014           4.60           6.87       42450             1
..    ...            ...            ...         ...           ...
296  2016           9.50          11.60       33988             1
297  2015           4.00           5.90       60000             1
298  2009           3.35          11.00       87934             1
299  2017          11.50          12.50        9000             1
300  2016           5.30           5.90        5464             1

[301 rows x 5 columns]

In [ ]:
X = df.drop("Selling_Price", axis=1).astype(float).values
Y = df["Selling_Price"].astype(float).values

x_mean = X.mean(axis=0)
x_std = X.std(axis=0)
y_mean = Y.mean(axis=0)
y_std = Y.std(axis=0)

X  = (X - x_mean) / x_std
Y = (Y - y_mean) / y_std

w = np.random.randn(X.shape[1])
b = 0

lr = 0.0001
epochs = 1000
losses = []


for i in range(epochs):

  y_pred = np.dot(X,w) + b

  loss = np.mean((Y-y_pred)**2)
  losses.append(loss)

  dw = (-2/len(X)) * np.dot(X.T, (Y-y_pred))
  db = (-2/len(X)) * np.sum(Y-y_pred)

  w -= lr * dw
  b -= lr * db

In [ ]:
def predict(new_data):

    data_normalization = (new_data - x_mean) / x_std

    y_pred_scaled = np.dot(data_normalization,w) + b

    y_pred_original = (y_pred_scaled * y_std) + y_mean

    return y_pred_original


sample = np.array([[2020, 1, 50000, 1]])
print("Predicted Price:", predict(sample))

Predicted Price: [4.15292688]